#TODO: FLOW OF EXECUTION
#TODO: RUN TWITTERLINKS, REDDITLINKS, RSSLINKS
#TODO: THEY ALL RETURN THEIR OWN JSON STRUCTURE
#TODO: EACH MUST GENERATE UNIQUE ID FOR EACH LINK (HASH TITLE+DATE+SOURCE?)
#TODO: DETERMINE FIELDS, THEN INSERT EVERYTHING INTO DB, CHECKING FOR DUPLICATES VIA UNIQUE ID

#TODO: DB SHOULD BE INSTANTIATED HERE AND PASSED TO ALL FUNCTIONS
#TODO: STAND UP DOCKER CONTAINER WITH MYSQLDB
#TODO: CONFIG IS READ IN HERE AND SETTINGS ARE PASSED ON TO EACH MODULE
#TODO: CONFIG: cred file location, all rss feeds to pull, all subreddits to parse.
