"""Export the feed catalog to a deterministic text snapshot.

The snapshot is split into three sections:
  - active feeds (enabled, not tombstoned)
  - disabled feeds (not enabled, not tombstoned) as commented lines
  - removed feeds (deleted_at IS NOT NULL) as commented lines

Output is sorted by normalized_url within each section so diffs are stable,
and a timestamped header records when the snapshot was taken.

A Publisher-side tool: identity comes from ``catalog.rss_feeds`` and the
failure detail from ``content.rss_feed_health``, so it needs a database URL.
Rendering is kept separate from reading, because the shape of this file is a
human-review artefact and has nothing to do with where the rows came from.

Usage:
    python export_rss_feeds.py [--config PATH] [--output PATH]
                               [--database-url URL]

``--output`` defaults to ``[sources.rss].export_path`` from the config. The
file is written atomically (write-temp + rename).
"""
from __future__ import annotations

import logging
import os
import sys
from datetime import UTC, datetime
from logging import StreamHandler
from logging.handlers import RotatingFileHandler
from pathlib import Path

import config as app_config
from publisher.connection import connect, resolve_database_url

logger = logging.getLogger(__name__)

_LOG_LEVEL_VALUES = {'CRITICAL': 50, 'ERROR': 40, 'WARNING': 30, 'INFO': 20, 'DEBUG': 10}

# Left join because health only exists once a feed has actually been fetched;
# a catalogued feed that has never run is not an error, it is just new.
_QUERY = """
    SELECT f.feed_url,
           f.normalized_url,
           f.enabled,
           f.deleted_at,
           h.last_error,
           COALESCE(h.consecutive_failures, 0) AS consecutive_failures
    FROM catalog.rss_feeds f
    LEFT JOIN content.rss_feed_health h ON h.normalized_url = f.normalized_url
    ORDER BY f.normalized_url COLLATE "C" ASC
"""


def configure_logging(log_file: Path, log_level_name: str) -> None:
    log_level = _LOG_LEVEL_VALUES.get(log_level_name, logging.INFO)
    logging.basicConfig(
        handlers=[
            RotatingFileHandler(log_file, maxBytes=1_000_000,
                                backupCount=5, encoding='utf8'),
            StreamHandler(),
        ],
        level=log_level,
        format='%(asctime)s (%(module)s) %(levelname)s - %(message)s',
        datefmt='%d/%m/%Y %I:%M:%S %p',
    )


# --- Rendering (no database) ------------------------------------------------

def _classify(rows):
    active, disabled, removed = [], [], []
    for row in rows:
        if row['deleted_at']:
            removed.append(row)
        elif row['enabled']:
            active.append(row)
        else:
            disabled.append(row)
    return active, disabled, removed


def render_snapshot(rows, generated_at: datetime, output_path: Path | None = None) -> str:
    """Return the deterministic snapshot text."""
    active, disabled, removed = _classify(rows)

    lines: list[str] = []
    lines.append(f'# Generated by export_rss_feeds.py at {generated_at.strftime("%Y-%m-%dT%H:%M:%SZ")}')
    lines.append(f'# active={len(active)}  disabled={len(disabled)}  removed={len(removed)}')
    lines.append('# The catalog is the live source of truth; this file is a snapshot copy.')
    if output_path is not None:
        lines.append(f'# Snapshot path: {output_path}')
    lines.append('')

    if active:
        lines.append(f'# --- active ({len(active)}) ---')
        for row in active:
            lines.append(row['feed_url'])
        lines.append('')

    if disabled:
        lines.append(f'# --- disabled ({len(disabled)}) ---')
        for row in disabled:
            reason = row.get('last_error') or ''
            failures = row.get('consecutive_failures') or 0
            suffix = f'  (failures={failures}'
            if reason:
                suffix += f' last_error={reason}'
            suffix += ')'
            lines.append(f'# {row["feed_url"]}{suffix}')
        lines.append('')

    if removed:
        lines.append(f'# --- removed ({len(removed)}) ---')
        for row in removed:
            ts = row.get('deleted_at') or 'unknown'
            lines.append(f'# {row["feed_url"]}  (removed {ts})')
        lines.append('')

    return '\n'.join(lines) + '\n'


def write_atomic(output_path: Path, text: str) -> None:
    tmp_path = output_path.with_name(f'{output_path.name}.tmp')
    if not output_path.parent.exists():
        output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        tmp_path.write_text(text, encoding='utf-8')
        os.replace(tmp_path, output_path)
    except PermissionError:
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        if not output_path.exists():
            raise
        output_path.write_text(text, encoding='utf-8')


# --- Reading ----------------------------------------------------------------

def read_feed_rows(conn) -> list[dict]:
    """Return every catalogued feed with its health detail, oldest key first."""
    with conn.cursor() as cur:
        cur.execute(_QUERY)
        columns = [d.name for d in cur.description]
        return [dict(zip(columns, row)) for row in cur.fetchall()]


def export_rss_feeds(conn, output_path: Path) -> dict:
    """Write a snapshot of the feed catalog to ``output_path``.

    Returns ``{'total', 'active', 'disabled', 'removed', 'output_path'}``.
    """
    rows = read_feed_rows(conn)
    active, disabled, removed = _classify(rows)
    text = render_snapshot(rows, datetime.now(UTC), output_path)
    write_atomic(output_path, text)
    return {
        'total': len(rows),
        'active': len(active),
        'disabled': len(disabled),
        'removed': len(removed),
        'output_path': str(output_path),
    }


def parse_arguments(argv: list[str] | None = None):
    import argparse
    parser = argparse.ArgumentParser(description='Export the feed catalog to a text snapshot.')
    parser.add_argument('--config', type=Path, default=app_config.DEFAULT_CONFIG,
                        help='Path to fetchlinks.toml')
    parser.add_argument('--output', type=Path, default=None,
                        help='Override the export path from [sources.rss].export_path')
    parser.add_argument('--database-url', default=None,
                        help='Override the database URL')
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_arguments(argv)
    try:
        cfg = app_config.load_config(args.config, require_credentials=False)
        configure_logging(cfg.paths.log_file, cfg.paths.log_level)

        if args.output:
            output_path = args.output.expanduser().resolve()
        elif cfg.sources.rss and cfg.sources.rss.export_path:
            output_path = cfg.sources.rss.export_path
        else:
            raise RuntimeError(
                '--output not given and [sources.rss].export_path is not set'
            )

        url = resolve_database_url(args.database_url)
        with connect(url) as conn:
            stats = export_rss_feeds(conn, output_path)
        logger.info(
            'Exported feed catalog: total=%s active=%s disabled=%s removed=%s -> %s',
            stats['total'], stats['active'], stats['disabled'],
            stats['removed'], stats['output_path'],
        )
        return 0
    except Exception as exc:
        logger.error('Export failed: %s', exc)
        return 1


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
