"""Export the rss_feeds DB table to a deterministic text snapshot.

The snapshot is split into three sections:
  - active feeds (enabled = 1, not tombstoned)
  - disabled feeds (enabled = 0, not tombstoned) as commented lines
  - removed feeds (deleted_at IS NOT NULL) as commented lines

Output is sorted by normalized_url within each section so diffs are stable.
A timestamped header records when the snapshot was taken.

Usage:
    python export_rss_feeds.py [--config PATH] [--output PATH]

``--output`` defaults to ``cfg.sources.rss.export_path`` from the loaded
config. The file is written atomically (write-temp + rename).
"""
from __future__ import annotations

import logging
import os
import sys
from datetime import UTC, datetime
from logging import StreamHandler
from logging.handlers import RotatingFileHandler
from pathlib import Path

import config as app_config
import db_utils

logger = logging.getLogger(__name__)

_LOG_LEVEL_VALUES = {'CRITICAL': 50, 'ERROR': 40, 'WARNING': 30, 'INFO': 20, 'DEBUG': 10}


def configure_logging(cfg: app_config.AppConfig) -> None:
    log_level = _LOG_LEVEL_VALUES.get(cfg.paths.log_level, logging.INFO)
    logging.basicConfig(
        handlers=[
            RotatingFileHandler(cfg.paths.log_file, maxBytes=1_000_000,
                                backupCount=5, encoding='utf8'),
            StreamHandler(),
        ],
        level=log_level,
        format='%(asctime)s (%(module)s) %(levelname)s - %(message)s',
        datefmt='%d/%m/%Y %I:%M:%S %p',
    )


def _classify(rows):
    active, disabled, removed = [], [], []
    for row in rows:
        if row['deleted_at']:
            removed.append(row)
        elif row['enabled']:
            active.append(row)
        else:
            disabled.append(row)
    return active, disabled, removed


def render_snapshot(rows, generated_at: datetime) -> str:
    """Return the deterministic snapshot text."""
    active, disabled, removed = _classify(rows)

    lines: list[str] = []
    lines.append(f'# Generated by export_rss_feeds.py at {generated_at.strftime("%Y-%m-%dT%H:%M:%SZ")}')
    lines.append(f'# active={len(active)}  disabled={len(disabled)}  removed={len(removed)}')
    lines.append('# DO NOT hand-edit on the VM; the DB is the source of truth.')
    lines.append('# To re-seed a fresh deployment, copy this file to /etc/fetchlinks/rss_feeds.txt.')
    lines.append('')

    if active:
        lines.append(f'# --- active ({len(active)}) ---')
        for row in active:
            lines.append(row['feed_url'])
        lines.append('')

    if disabled:
        lines.append(f'# --- disabled ({len(disabled)}) ---')
        for row in disabled:
            reason = row.get('last_error') or ''
            failures = row.get('consecutive_failures') or 0
            suffix = f'  (failures={failures}'
            if reason:
                suffix += f' last_error={reason}'
            suffix += ')'
            lines.append(f'# {row["feed_url"]}{suffix}')
        lines.append('')

    if removed:
        lines.append(f'# --- removed ({len(removed)}) ---')
        for row in removed:
            ts = row.get('deleted_at') or 'unknown'
            lines.append(f'# {row["feed_url"]}  (removed {ts})')
        lines.append('')

    return '\n'.join(lines) + '\n'


def write_atomic(output_path: Path, text: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = output_path.with_name(f'{output_path.name}.tmp')
    tmp_path.write_text(text, encoding='utf-8')
    os.replace(tmp_path, output_path)


def export_rss_feeds(db_path: Path, output_path: Path) -> dict:
    """Read every feed from the DB and write a snapshot to ``output_path``.

    Returns ``{'total', 'active', 'disabled', 'removed', 'output_path'}``.
    """
    rows = db_utils.db_get_all_rss_feeds(db_path)
    active, disabled, removed = _classify(rows)
    text = render_snapshot(rows, datetime.now(UTC))
    write_atomic(output_path, text)
    return {
        'total': len(rows),
        'active': len(active),
        'disabled': len(disabled),
        'removed': len(removed),
        'output_path': str(output_path),
    }


def parse_arguments(argv: list[str] | None = None):
    import argparse
    parser = argparse.ArgumentParser(description='Export rss_feeds to a text snapshot.')
    parser.add_argument('--config', type=Path, default=app_config.DEFAULT_CONFIG,
                        help='Path to fetchlinks.toml')
    parser.add_argument('--output', type=Path, default=None,
                        help='Override the export path from [sources.rss].export_path')
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_arguments(argv)
    try:
        cfg = app_config.load_config(args.config)
        configure_logging(cfg)

        if args.output:
            output_path = args.output.expanduser().resolve()
        elif cfg.sources.rss and cfg.sources.rss.export_path:
            output_path = cfg.sources.rss.export_path
        else:
            raise RuntimeError(
                '--output not given and [sources.rss].export_path is not set'
            )

        stats = export_rss_feeds(cfg.paths.db, output_path)
        logger.info(
            'Exported rss_feeds: total=%s active=%s disabled=%s removed=%s -> %s',
            stats['total'], stats['active'], stats['disabled'],
            stats['removed'], stats['output_path'],
        )
        return 0
    except Exception as exc:
        logging.exception('export_rss_feeds failed: %s', exc)
        raise SystemExit(1) from exc


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
