"""Export the rss_feeds DB table to a deterministic text snapshot.

The snapshot is split into three sections:
  - active feeds (enabled = 1, not tombstoned)
  - disabled feeds (enabled = 0, not tombstoned) as commented lines
  - removed feeds (deleted_at IS NOT NULL) as commented lines

Output is sorted by normalized_url within each section so diffs are stable.
A timestamped header records when the snapshot was taken.

Usage:
    python export_rss_feeds.py [--config PATH] [--output PATH]

``--output`` defaults to ``cfg.sources.rss.export_path`` from the loaded
config. The file is written atomically (write-temp + rename).
"""
from __future__ import annotations

import logging
import os
import sys
import tomllib
from dataclasses import dataclass
from datetime import UTC, datetime
from logging import StreamHandler
from logging.handlers import RotatingFileHandler
from pathlib import Path

import config as app_config
import db_utils

logger = logging.getLogger(__name__)

_LOG_LEVEL_VALUES = {'CRITICAL': 50, 'ERROR': 40, 'WARNING': 30, 'INFO': 20, 'DEBUG': 10}


@dataclass(frozen=True)
class ExportConfig:
    db_path: Path
    control_db_path: Path
    log_file: Path
    log_level: str
    export_path: Path | None


def configure_logging(log_file: Path, log_level_name: str) -> None:
    log_level = _LOG_LEVEL_VALUES.get(log_level_name, logging.INFO)
    logging.basicConfig(
        handlers=[
            RotatingFileHandler(log_file, maxBytes=1_000_000,
                                backupCount=5, encoding='utf8'),
            StreamHandler(),
        ],
        level=log_level,
        format='%(asctime)s (%(module)s) %(levelname)s - %(message)s',
        datefmt='%d/%m/%Y %I:%M:%S %p',
    )


def _resolve_config_path(value, base: Path) -> Path:
    if not isinstance(value, str) or not value.strip():
        raise ValueError('Path value must be a non-empty string')
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = (base / path).resolve()
    return path


def load_export_config(config_path: Path) -> ExportConfig:
    config_path = Path(config_path)
    if not config_path.exists():
        raise FileNotFoundError(f'Config file does not exist: {config_path}')

    with open(config_path, 'rb') as fh:
        raw = tomllib.load(fh)

    base = config_path.resolve().parent
    paths = raw.get('paths', {})
    if not isinstance(paths, dict):
        raise ValueError('[paths] must be a table')
    for required in ('db', 'log_file'):
        if required not in paths:
            raise ValueError(f'[paths] missing required field: {required}')

    sources = raw.get('sources', {})
    if not isinstance(sources, dict):
        raise ValueError('[sources] must be a table')
    rss = sources.get('rss', {})
    if rss is None:
        rss = {}
    if not isinstance(rss, dict):
        raise ValueError('[sources.rss] must be a table')

    export_value = rss.get('export_path')
    log_level = str(paths.get('log_level', 'INFO')).upper()
    if log_level not in _LOG_LEVEL_VALUES:
        raise ValueError(f'[paths] log_level must be one of {sorted(_LOG_LEVEL_VALUES)}')

    log_file = _resolve_config_path(paths['log_file'], base)
    log_file.parent.mkdir(parents=True, exist_ok=True)
    db_path = _resolve_config_path(paths['db'], base)
    # control_db is optional; when unset the catalog shares the data db file.
    if 'control_db' in paths:
        control_db_path = _resolve_config_path(paths['control_db'], base)
    else:
        control_db_path = db_path
    return ExportConfig(
        db_path=db_path,
        control_db_path=control_db_path,
        log_file=log_file,
        log_level=log_level,
        export_path=_resolve_config_path(export_value, base) if export_value else None,
    )


def _classify(rows):
    active, disabled, removed = [], [], []
    for row in rows:
        if row['deleted_at']:
            removed.append(row)
        elif row['enabled']:
            active.append(row)
        else:
            disabled.append(row)
    return active, disabled, removed


def render_snapshot(rows, generated_at: datetime, output_path: Path | None = None) -> str:
    """Return the deterministic snapshot text."""
    active, disabled, removed = _classify(rows)

    lines: list[str] = []
    lines.append(f'# Generated by export_rss_feeds.py at {generated_at.strftime("%Y-%m-%dT%H:%M:%SZ")}')
    lines.append(f'# active={len(active)}  disabled={len(disabled)}  removed={len(removed)}')
    lines.append('# The DB is the live source of truth; this file is a snapshot copy.')
    if output_path is not None:
        lines.append(f'# Snapshot path: {output_path}')
    lines.append('')

    if active:
        lines.append(f'# --- active ({len(active)}) ---')
        for row in active:
            lines.append(row['feed_url'])
        lines.append('')

    if disabled:
        lines.append(f'# --- disabled ({len(disabled)}) ---')
        for row in disabled:
            reason = row.get('last_error') or ''
            failures = row.get('consecutive_failures') or 0
            suffix = f'  (failures={failures}'
            if reason:
                suffix += f' last_error={reason}'
            suffix += ')'
            lines.append(f'# {row["feed_url"]}{suffix}')
        lines.append('')

    if removed:
        lines.append(f'# --- removed ({len(removed)}) ---')
        for row in removed:
            ts = row.get('deleted_at') or 'unknown'
            lines.append(f'# {row["feed_url"]}  (removed {ts})')
        lines.append('')

    return '\n'.join(lines) + '\n'


def write_atomic(output_path: Path, text: str) -> None:
    tmp_path = output_path.with_name(f'{output_path.name}.tmp')
    if not output_path.parent.exists():
        output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        tmp_path.write_text(text, encoding='utf-8')
        os.replace(tmp_path, output_path)
    except PermissionError:
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        if not output_path.exists():
            raise
        output_path.write_text(text, encoding='utf-8')


def export_rss_feeds(db_path: Path, output_path: Path,
                     control_db_path: Path | None = None) -> dict:
    """Read every feed from the DB and write a snapshot to ``output_path``.

    Identity comes from ``control_db_path`` (defaults to ``db_path``) and
    health from ``db_path``; in single-host mode they are the same file.

    Returns ``{'total', 'active', 'disabled', 'removed', 'output_path'}``.
    """
    rows = db_utils.db_get_all_rss_feeds(control_db_path or db_path, db_path)
    active, disabled, removed = _classify(rows)
    text = render_snapshot(rows, datetime.now(UTC), output_path)
    write_atomic(output_path, text)
    return {
        'total': len(rows),
        'active': len(active),
        'disabled': len(disabled),
        'removed': len(removed),
        'output_path': str(output_path),
    }


def parse_arguments(argv: list[str] | None = None):
    import argparse
    parser = argparse.ArgumentParser(description='Export rss_feeds to a text snapshot.')
    parser.add_argument('--config', type=Path, default=app_config.DEFAULT_CONFIG,
                        help='Path to fetchlinks.toml')
    parser.add_argument('--output', type=Path, default=None,
                        help='Override the export path from [sources.rss].export_path')
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_arguments(argv)
    try:
        cfg = load_export_config(args.config)
        configure_logging(cfg.log_file, cfg.log_level)

        if args.output:
            output_path = args.output.expanduser().resolve()
        elif cfg.export_path:
            output_path = cfg.export_path
        else:
            raise RuntimeError(
                '--output not given and [sources.rss].export_path is not set'
            )

        stats = export_rss_feeds(cfg.db_path, output_path, cfg.control_db_path)
        logger.info(
            'Exported rss_feeds: total=%s active=%s disabled=%s removed=%s -> %s',
            stats['total'], stats['active'], stats['disabled'],
            stats['removed'], stats['output_path'],
        )
        return 0
    except Exception as exc:
        logging.exception('export_rss_feeds failed: %s', exc)
        raise SystemExit(1) from exc


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
