FROM ubuntu:16.04

# Install.
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y curl git htop man unzip vim wget python3

# Add files.
# ADD /home/rich/Documents/SCRIPTS/PROJECTS/TWITTERLINKS/ /root/TWITTERLINKS/

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["/bin/bash"]
